import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <header>
          <Link href={'/'}>
                <h1>Dusky Desk</h1>
            </Link>

          <nav>
            <ul>
              <li>Read</li>
              <li>About</li>
              <li>Contact</li>
            </ul>
          </nav>
        </header>

        {children}
      
        <footer>
          © <Link href={'https://github.com/USKhokhar'} target='_blank'>
            U.S.Khokhar
          </Link>
        </footer>
      </body>
    </html>
  )
}
